/**
 * Shell-init helpers for PTYs supergit spawns.
 *
 * Right now this is just zsh history hardening: when we spawn the
 * user's login shell for a `terminal` column, we set up a temp
 * `ZDOTDIR` whose `.zshrc` sources the user's real `~/.zshrc` and
 * then forces sane history options. The user keeps all their normal
 * config; we just guarantee three things on top:
 *
 *   1. `HISTFILE` / `HISTSIZE` / `SAVEHIST` are set to reasonable
 *      values if the user hasn't set them (stock macOS leaves
 *      HISTSIZE=10 / SAVEHIST=0 → arrow-up shows nothing).
 *   2. `INC_APPEND_HISTORY` — every command is appended to the
 *      histfile immediately, not on shell exit. This matters
 *      because supergit's PTY can be killed mid-session (browser
 *      tab closed, helper restart) and the default "flush on exit"
 *      behavior would lose every command typed in that column.
 *   3. `SHARE_HISTORY` — arrow-up in one supergit shell column
 *      sees commands typed in another column. Matches what users
 *      expect from a "dashboard with many terminals" UX.
 *
 * bash / fish / pwsh: not handled. bash needs a `--rcfile` trick;
 * fish persists history automatically; PSReadLine on PowerShell
 * persists by default. Future work.
 */

import { mkdtemp, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";

/** Heredoc-style snippet appended to the user's .zshrc when supergit
 *  spawns a zsh shell. Idempotent — every `[[ -z "$VAR" ]]` guard
 *  means we never clobber an explicit user preference. */
export const ZSH_HISTORY_SNIPPET = `# supergit: harden zsh history so arrow-up works and commands persist
# across crashed sessions / closed browser tabs. Defaults are applied
# only when the corresponding variable is empty or zero, so a user
# who's already set HISTSIZE etc. keeps their values.
[[ -z "\${HISTFILE-}" ]] && HISTFILE="\${HOME}/.zsh_history"
[[ -z "\${HISTSIZE-}" || "\${HISTSIZE-}" = "0" ]] && HISTSIZE=10000
[[ -z "\${SAVEHIST-}" || "\${SAVEHIST-}" = "0" ]] && SAVEHIST=10000
setopt INC_APPEND_HISTORY SHARE_HISTORY EXTENDED_HISTORY
`;

/** True when the cmd[] supergit is about to spawn is a zsh shell.
 *  Matches `zsh`, `/bin/zsh`, `/usr/local/bin/zsh-5.9`. Does NOT
 *  match bash/fish/sh/dash — those use other init mechanisms. */
export function isZshCmd(cmd: readonly string[]): boolean {
  if (!cmd.length) return false;
  const base = basename(cmd[0] ?? "");
  return base === "zsh" || /^zsh-\d/.test(base);
}

/** Build a temp ZDOTDIR for a zsh PTY: a `.zshrc` that sources the
 *  user's real ~/.zshrc then appends our history-hardening snippet.
 *  Returns the directory path so the caller can set
 *  `ZDOTDIR=<path>` in the PTY env and call cleanupZdotdir() on
 *  exit. */
export async function makeZshZdotdir(): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), "supergit-zsh-"));
  const rc =
    "# Auto-generated by supergit. Sources your real ~/.zshrc then\n" +
    "# appends history-hardening defaults.\n" +
    "if [[ -f \"$HOME/.zshrc\" ]]; then\n" +
    "  source \"$HOME/.zshrc\"\n" +
    "fi\n" +
    ZSH_HISTORY_SNIPPET;
  await writeFile(join(dir, ".zshrc"), rc, "utf-8");
  return dir;
}

/** Remove a temp ZDOTDIR. Best-effort — tempfiles get GC'd by the
 *  OS anyway, so a failure here is not worth surfacing. */
export async function cleanupZdotdir(dir: string): Promise<void> {
  try {
    await rm(dir, { recursive: true, force: true });
  } catch {
    /* swallow */
  }
}
