/**
 * Persisted set of "expanded" UI items (e.g. worktree paths whose commit
 * history is shown).
 *
 * The storage is injected (a tiny KVStore interface) so this class is
 * testable without a real browser. Production calls `new ExpandedStore(
 * window.localStorage, "supergit:commitsExpanded")`; tests pass an in-
 * memory map.
 */

export interface KVStore {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
}

export class ExpandedStore {
  constructor(
    private readonly storage: KVStore,
    private readonly key: string,
  ) {}

  /** Returns the set of currently-expanded paths. Tolerant of corrupt storage. */
  load(): Set<string> {
    let raw: string | null;
    try {
      raw = this.storage.getItem(this.key);
    } catch {
      return new Set();
    }
    if (raw === null) return new Set();
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      return new Set();
    }
    if (!Array.isArray(parsed)) return new Set();
    return new Set(parsed.filter((x): x is string => typeof x === "string"));
  }

  /** Persists the given paths. Errors (quota, private-mode, etc.) are swallowed. */
  save(paths: Iterable<string>): void {
    try {
      this.storage.setItem(this.key, JSON.stringify([...paths]));
    } catch {
      // ignore — persistence is best-effort
    }
  }
}

/**
 * Persisted set of "dismissed" session sources. Sessions in this set
 * are pushed into a separate "Dismissed" group at the bottom of the
 * session picker so the active list stays clean. Restoring removes
 * the source from the set. Same shape / corruption-tolerance as
 * ExpandedStore — keyed on the session's stable `source` string.
 */
export class DismissedSessionsStore {
  constructor(
    private readonly storage: KVStore,
    private readonly key: string,
  ) {}

  load(): Set<string> {
    let raw: string | null;
    try {
      raw = this.storage.getItem(this.key);
    } catch {
      return new Set();
    }
    if (raw === null) return new Set();
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      return new Set();
    }
    if (!Array.isArray(parsed)) return new Set();
    return new Set(parsed.filter((x): x is string => typeof x === "string"));
  }

  save(sources: Iterable<string>): void {
    try {
      this.storage.setItem(this.key, JSON.stringify([...sources]));
    } catch {
      // ignore — persistence is best-effort
    }
  }
}

/**
 * Persisted map of "which sessions were open under which worktree". Survives
 * page reloads so the user lands back where they were. Same KVStore-injection
 * pattern as ExpandedStore so it's testable without a real browser.
 */
export type PersistedAgent = "claude" | "codex" | "copilot" | "shell";

export interface PersistedSession {
  agent: PersistedAgent;
  source: string;
  /** Optional. Stamped onto `__new__:claude:` / `__new__:codex:` entries
   *  the first time the daemon's activity-tail surfaces a real agent-side
   *  session id for that (cwd, agent). On a subsequent mount (notably
   *  after a hard reload that outlives the daemon's PTY-grace window) we
   *  spawn `claude --resume <sid>` instead of bare `claude`, so the
   *  conversation continues instead of starting over. */
  resumeSessionId?: string;
  /** Optional. UUID generated by `openNewAgentSession` for brand-new
   *  Claude columns and passed as `claude --session-id <uuid>` on spawn.
   *  Forces a fresh conversation even when Claude CLI would otherwise
   *  auto-load the cwd's most-recent session. Persisted so that a
   *  reload before the JSONL appears re-spawns with the same id (the
   *  daemon's PTY-grace window keeps the original PTY alive in most
   *  cases, but if the daemon was restarted the next mount must still
   *  land on the same session file). Once `resumeSessionId` is stamped,
   *  this becomes ignored — the resume path takes over. */
  preassignedSessionId?: string;
  /** Optional. When `"terminal"`, the SessionView column for this source
   *  was last seen with "Resume in terminal" mode active (i.e. the user
   *  flipped from the markdown chat view to a live `claude --resume`
   *  PTY). On remount, the column should re-enter terminal mode so a
   *  page reload doesn't drop the user back to the read-only history.
   *  Absence implies the default `"read"` mode. */
  mode?: "terminal";
}

const VALID_AGENTS: ReadonlySet<PersistedAgent> = new Set([
  "claude",
  "codex",
  "copilot",
  // Terminal columns (plain `$SHELL` PTYs) live in `openSessionsByWt`
  // alongside agents. Without "shell" here, `sanitizeSession` strips
  // every persisted shell entry on `OpenSessionsStore.load()` — the
  // disposed-terminal-column-disappears-after-reload bug.
  "shell",
]);

function sanitizeSession(item: unknown): PersistedSession | null {
  if (typeof item !== "object" || item === null) return null;
  const o = item as Record<string, unknown>;
  if (typeof o.source !== "string" || o.source.length === 0) return null;
  if (typeof o.agent !== "string") return null;
  if (!VALID_AGENTS.has(o.agent as PersistedAgent)) return null;
  const out: PersistedSession = {
    agent: o.agent as PersistedAgent,
    source: o.source,
  };
  if (typeof o.resumeSessionId === "string" && o.resumeSessionId.length > 0) {
    out.resumeSessionId = o.resumeSessionId;
  }
  if (
    typeof o.preassignedSessionId === "string" &&
    o.preassignedSessionId.length > 0
  ) {
    out.preassignedSessionId = o.preassignedSessionId;
  }
  if (o.mode === "terminal") {
    out.mode = "terminal";
  }
  return out;
}

export class OpenSessionsStore {
  constructor(
    private readonly storage: KVStore,
    private readonly key: string,
  ) {}

  /** Returns the persisted map. Tolerates garbage at any level. */
  load(): Record<string, PersistedSession[]> {
    let raw: string | null;
    try {
      raw = this.storage.getItem(this.key);
    } catch {
      return {};
    }
    if (raw === null) return {};
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      return {};
    }
    if (
      typeof parsed !== "object" ||
      parsed === null ||
      Array.isArray(parsed)
    ) {
      return {};
    }
    const out: Record<string, PersistedSession[]> = {};
    for (const [wtPath, value] of Object.entries(
      parsed as Record<string, unknown>,
    )) {
      if (typeof wtPath !== "string" || wtPath.length === 0) continue;
      if (!Array.isArray(value)) continue;
      const list: PersistedSession[] = [];
      const seen = new Set<string>();
      for (const item of value) {
        const s = sanitizeSession(item);
        if (!s) continue;
        if (seen.has(s.source)) continue; // de-dupe by source
        seen.add(s.source);
        list.push(s);
      }
      if (list.length > 0) out[wtPath] = list;
    }
    return out;
  }

  /** Persists the map. Errors (quota / privacy mode) are swallowed. */
  save(data: Record<string, PersistedSession[]>): void {
    try {
      this.storage.setItem(this.key, JSON.stringify(data));
    } catch {
      // best-effort
    }
  }
}

/** Source prefixes the daemon doesn't list in `/api/agents` but the UI
 *  still wants to render: brand-new agent sessions before their JSONL
 *  has appeared on disk, plus Terminal-column shells (which are entirely
 *  workspace-owned and never show up in the agent snapshot). Centralised
 *  so the render-time filter and the persistence layer agree on what
 *  counts as a "synthetic" source. */
export const SYNTHETIC_SOURCE_PREFIXES = [
  // Brand-new agent or shell session — TUI is up, JSONL not yet on disk
  // (or, for shells, never indexed by agentsForWorktree at all).
  "__new__:",
  // Reattached shell after a UI reload — TerminalView skips spawn and
  // connects to an existing live PTY via WS.
  "__attached__:",
  // Past-shell read-mode column — ShellView renders the transcript and
  // a Resume button.
  "__transcript__:",
] as const;

/**
 * Filter a persisted list to sessions whose source file is still detected
 * by the daemon (i.e. present in the current `/api/agents` snapshot) OR
 * whose source is a known supergit-internal synthetic prefix (new TUI
 * spawns, live shell reattaches, past-shell read-mode columns).
 *
 * IMPORTANT: this is a *render-time* filter. Callers must keep the
 * unfiltered list in persistence — if a session file vanishes
 * temporarily (file moved, tool not running) we hide it from the UI but
 * do NOT drop it from saved state. When the source reappears the row
 * shows up again on the next load.
 */
export function filterToExistingSessions(
  persisted: PersistedSession[],
  existingSources: ReadonlySet<string>,
): PersistedSession[] {
  return persisted.filter(
    (s) =>
      SYNTHETIC_SOURCE_PREFIXES.some((p) => s.source.startsWith(p)) ||
      existingSources.has(s.source),
  );
}

/** Build the cmd[] supergit should hand to a `TerminalView` mounted in
 *  a transient (`__new__:` / `__attached__:`) column.
 *
 *  For shells, it's the user's default login shell — agent doesn't matter.
 *
 *  For agent TUIs the rule is:
 *  - **no `resumeSessionId`** (the brand-new spawn, JSONL not yet on
 *    disk): the bare agent CLI. Claude/Codex will mint their own
 *    session id and start writing it.
 *  - **`resumeSessionId` stamped** (the activity tail has surfaced the
 *    real session id, either earlier in this tab or persisted from a
 *    prior tab/before-reload): `claude --resume <sid>
 *    --allow-dangerously-skip-permissions` / `codex resume <sid>`. This
 *    is the path that makes hard reloads non-destructive — without it,
 *    every reload of a live agent column starts a fresh conversation. */
export function cmdForOpenSession(
  s: {
    agent: PersistedAgent | "shell";
    resumeSessionId?: string;
    preassignedSessionId?: string;
  },
  defaultShell: string,
): string[] {
  // Spawn the shell as a *login* shell (`-l`). Without `-l`, zsh is
  // interactive (TTY detected) but doesn't source `.zprofile`/`.zlogin`,
  // and on stock macOS that's where many users (or system defaults the
  // user inherits from) set HISTFILE / HISTSIZE / SAVEHIST. The defaults
  // when those are unset are brutal: HISTSIZE=10, SAVEHIST=0 → arrow-up
  // shows nothing on a fresh column and the in-session commands are
  // discarded on Dispose. Terminal.app and iTerm2 start the user's shell
  // as a login shell for the same reason. The flag is recognized by zsh,
  // bash, fish, and sh — the only shells supergit advertises support for.
  if (s.agent === "shell") return [defaultShell, "-l"];
  const sid = s.resumeSessionId;
  if (s.agent === "claude") {
    if (sid) {
      return [
        "claude",
        "--resume",
        sid,
        "--allow-dangerously-skip-permissions",
      ];
    }
    // Force a fresh session id for brand-new columns so recent Claude
    // versions can't auto-load the cwd's most-recent conversation
    // (`claude` alone has started doing this; --session-id makes it
    // deterministic).
    if (s.preassignedSessionId) {
      return ["claude", "--session-id", s.preassignedSessionId];
    }
    return ["claude"];
  }
  if (s.agent === "codex") {
    if (sid) return ["codex", "resume", sid];
    return ["codex"];
  }
  // copilot has no resume semantics in v0
  return [s.agent];
}

/** Attach the real agent-side session id to the first matching
 *  `__new__:<agent>:` column in the given worktree that doesn't have one
 *  yet. The match key is `(cwd, agent)`. Returns a new map only when
 *  something actually changed — same reference otherwise, so reactive
 *  consumers can `if (next !== prev)` to skip work.
 *
 *  Why "first unstamped wins": if the user has two simultaneous
 *  `__new__:claude:` columns in the same worktree (opened sequentially),
 *  the activity tail will surface each new sessionId as its JSONL
 *  appears. Each event lands on the next column that hasn't been
 *  stamped yet. Concurrent opens (rare) may attribute incorrectly;
 *  acceptable until we plumb the sessionId back from the spawning side. */
/** Update the persisted `mode` for one (wtPath, source) entry without
 *  disturbing anything else. `"terminal"` adds the field; `"read"` drops
 *  it (absence is the default and we don't want to leave dead state
 *  behind once the user disposes a TUI). Returns the same map reference
 *  when nothing changed — same short-circuit contract as
 *  `stampDiscoveredSessionId`. */
export function setSessionMode(
  byWt: Record<string, PersistedSession[]>,
  wtPath: string,
  source: string,
  mode: "read" | "terminal",
): Record<string, PersistedSession[]> {
  const list = byWt[wtPath];
  if (!list) return byWt;
  const idx = list.findIndex((s) => s.source === source);
  if (idx === -1) return byWt;
  const current = list[idx]!;
  const currentMode = current.mode === "terminal" ? "terminal" : "read";
  if (currentMode === mode) return byWt;
  const updated: PersistedSession = { ...current };
  if (mode === "terminal") updated.mode = "terminal";
  else delete updated.mode;
  const next = list.slice();
  next[idx] = updated;
  return { ...byWt, [wtPath]: next };
}

export function stampDiscoveredSessionId(
  byWt: Record<string, PersistedSession[]>,
  ev: { agent: PersistedAgent; cwd: string; sessionId: string },
): Record<string, PersistedSession[]> {
  const res = stampDiscoveredSessionIdWithDetail(byWt, ev);
  return res.byWt;
}

/** Same as `stampDiscoveredSessionId` but also returns the synthetic
 *  source of the column that was just stamped (if any). The caller can
 *  use it to migrate a server-side title from the synthetic key to the
 *  real JSONL path (`ev.source` at the call site) — see
 *  [[feedback-titles-linked-to-real-session-ids]] for the bug this
 *  fixes (titles staying on disposable synthetic keys after the agent's
 *  JSONL takes over).
 *
 *  `stampedSource` is `null` when nothing matched (no churn), so the
 *  caller can short-circuit the migrate POST. */
export function stampDiscoveredSessionIdWithDetail(
  byWt: Record<string, PersistedSession[]>,
  ev: { agent: PersistedAgent; cwd: string; sessionId: string },
): { byWt: Record<string, PersistedSession[]>; stampedSource: string | null } {
  if (!ev.sessionId) return { byWt, stampedSource: null };
  const list = byWt[ev.cwd];
  if (!list || list.length === 0) return { byWt, stampedSource: null };
  const prefix = `__new__:${ev.agent}:`;
  const idx = list.findIndex(
    (s) =>
      s.agent === ev.agent &&
      s.source.startsWith(prefix) &&
      !s.resumeSessionId,
  );
  if (idx === -1) return { byWt, stampedSource: null };
  const target = list[idx]!;
  const next = list.slice();
  next[idx] = { ...target, resumeSessionId: ev.sessionId };
  return {
    byWt: { ...byWt, [ev.cwd]: next },
    stampedSource: target.source,
  };
}

/** Where should the manual title for a still-transient (`__new__:<agent>:…`)
 *  column be stored? Once the activity tail has surfaced a real agent
 *  session id and we can match it back to its JSONL path, the title
 *  belongs there — that way a hard reload (which re-mints synthetic ids
 *  on the *next* spawn) still surfaces the user's named title against
 *  whatever conversation the agent is actually resuming. Before that,
 *  fall back to the synthetic source so an unfinished name doesn't get
 *  silently dropped. */
export function resolveTitleSource(
  session: { source: string; resumeSessionId?: string; agent: PersistedAgent | "shell" },
  agents: ReadonlyArray<{ agent: string; sessionId?: string; source: string }>,
): string {
  if (!session.source.startsWith("__new__:")) return session.source;
  const sid = session.resumeSessionId;
  if (!sid) return session.source;
  const match = agents.find(
    (a) => a.agent === session.agent && a.sessionId === sid,
  );
  return match?.source ?? session.source;
}

/**
 * Persisted "which worktrees of each repo should appear as rows in the
 * dashboard". Storage shape: { [repoId]: string[] } where strings are
 * worktree paths.
 *
 * The dashboard used to flat-list every worktree of every registered
 * repo. That gets noisy fast on repos with many branches, so the user
 * controls visibility explicitly: adding a repo defaults to showing
 * only the main worktree; the worktree picker toggles others in / out.
 *
 * Persistence is per-browser (localStorage). Daemon doesn't see this —
 * which is fine; it's a presentation concern, not workspace state.
 */
export class VisibleWorktreesStore {
  constructor(
    private readonly storage: KVStore,
    private readonly key: string,
  ) {}

  load(): Record<string, string[]> {
    let raw: string | null;
    try {
      raw = this.storage.getItem(this.key);
    } catch {
      return {};
    }
    if (raw === null) return {};
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      return {};
    }
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
      return {};
    }
    const out: Record<string, string[]> = {};
    for (const [repoId, value] of Object.entries(parsed as Record<string, unknown>)) {
      if (!Array.isArray(value)) continue;
      out[repoId] = value.filter((x): x is string => typeof x === "string" && x.length > 0);
    }
    return out;
  }

  save(map: Record<string, string[]>): void {
    try {
      // Strip empty arrays + non-string entries on the way out so we
      // don't accumulate garbage.
      const sanitized: Record<string, string[]> = {};
      for (const [k, v] of Object.entries(map)) {
        const paths = (v ?? []).filter((p) => typeof p === "string" && p.length > 0);
        if (paths.length > 0) sanitized[k] = paths;
      }
      this.storage.setItem(this.key, JSON.stringify(sanitized));
    } catch {
      // ignore — best-effort
    }
  }
}

/**
 * Compute the effective list of worktree paths to render for a given
 * repo, applying defaults for repos with no stored visibility yet.
 *
 * Default behaviour: when no entry exists for the repo, fall back to
 * showing **the first worktree only**. (The first one from `git
 * worktree list` is the original / main worktree of the repo.)
 *
 * Caller is responsible for passing the *current* set of on-disk
 * worktrees — any path in the stored list that no longer exists on
 * disk is silently dropped so removed worktrees don't haunt the UI.
 */
export function effectiveVisibleWorktrees(
  repoId: string,
  diskWorktreePaths: string[],
  stored: Record<string, string[]>,
): string[] {
  if (diskWorktreePaths.length === 0) return [];
  const entry = stored[repoId];
  if (entry === undefined) {
    return [diskWorktreePaths[0]!];
  }
  const onDisk = new Set(diskWorktreePaths);
  return entry.filter((p) => onDisk.has(p));
}
