#!/usr/bin/env bun
import { resolve, join } from "node:path";
import { existsSync, statSync } from "node:fs";
import { readdir } from "node:fs/promises";
import { $ } from "bun";

const ROOT = resolve(import.meta.dir, "..");
const platform = `${process.platform}-${process.arch}`;
const isWin = process.platform === "win32";

const paths: Record<string, string> = {
  flat: resolve(ROOT, "build/supergit-native"),
};
if (process.platform === "darwin") {
  paths.app = resolve(ROOT, `build/stable-${platform === "darwin-arm64" ? "macos-arm64" : platform}/Supergit.app`);
  paths.dmg = resolve(ROOT, "artifacts", `stable-macos-arm64-Supergit.dmg`);
}
if (isWin) {
  paths.setup = resolve(ROOT, "build/stable-win-x64/Supergit-Setup.exe");
  paths.archive = resolve(ROOT, "build/stable-win-x64/Supergit-Setup.tar.zst");
}

// Cross-platform recursive size (avoids `du`, which doesn't exist on Windows).
async function sizeOf(path: string): Promise<string> {
  async function walk(p: string): Promise<number> {
    const s = statSync(p);
    if (!s.isDirectory()) return s.size;
    let total = 0;
    for (const entry of await readdir(p)) total += await walk(join(p, entry));
    return total;
  }
  const bytes = await walk(path);
  return `${(bytes / 1024 / 1024).toFixed(1)}M`;
}

// Post-build: stamp the Setup.exe installer with the icon too (it's
// generated by electrobun after our pre-build stamp of bun.exe/launcher.exe).
if (isWin) {
  const rcedit = resolve(ROOT, "node_modules/rcedit/bin/rcedit-x64.exe");
  const ico = resolve(ROOT, "icon.ico");
  if (existsSync(rcedit) && existsSync(ico) && paths.setup && existsSync(paths.setup)) {
    try {
      await $`${rcedit} ${paths.setup} --set-icon ${ico} --set-version-string ProductName Supergit --set-version-string FileDescription Supergit --set-file-version 0.1.0 --set-product-version 0.1.0`.quiet();
      console.log(`  icon+meta → ${paths.setup}`);
    } catch (e) {
      console.warn(`  ⚠ rcedit failed for Setup.exe: ${e}`);
    }
  }
}

console.log(`\n=== supergit build complete ===\n`);

for (const [label, path] of Object.entries(paths)) {
  if (existsSync(path)) {
    console.log(`  ${label.padEnd(7)} ${path}  (${await sizeOf(path)})`);
  }
}

// Open / focus the output directory so the user can grab the installer.
if (paths.app && existsSync(paths.app)) {
  console.log(`\n  open ${paths.app}\n`);
  await $`open -R ${paths.app}`.nothrow().quiet();
} else if (isWin && paths.setup && existsSync(paths.setup)) {
  const setupDir = resolve(paths.setup, "..");
  console.log(`\n  Opening:  ${setupDir}\n`);
  await $`explorer ${setupDir}`.nothrow().quiet();
}
