#!/usr/bin/env bun
import { resolve, join } from "node:path";
import { existsSync, statSync, readdirSync, rmSync } from "node:fs";
import { readdir } from "node:fs/promises";
import { $ } from "bun";

const ROOT = resolve(import.meta.dir, "..");
const isWin = process.platform === "win32";
const APP_NAME = "Treetop";

const paths: Record<string, string> = {
  flat: resolve(ROOT, "build/supergit-native"),
};
if (process.platform === "darwin") {
  const macArch = process.arch === "arm64" ? "macos-arm64" : "macos-x64";
  paths.app = resolve(ROOT, `build/stable-${macArch}/${APP_NAME}.app`);
  paths.dmg = resolve(ROOT, "artifacts", `stable-${macArch}-${APP_NAME}.dmg`);
}
if (isWin) {
  paths.setup = resolve(ROOT, `build/stable-win-x64/${APP_NAME}-Setup.exe`);
  paths.archive = resolve(ROOT, `build/stable-win-x64/${APP_NAME}-Setup.tar.zst`);
}

// Electrobun stable builds produce a self-extracting .app that decompresses on
// first launch. We pre-extract it here so the build output is ready to run
// immediately (no "open once to initialize" step needed for AirDrop/sharing).
if (process.platform === "darwin" && paths.app && existsSync(paths.app)) {
  const resources = join(paths.app, "Contents", "Resources");
  const zstFile = readdirSync(resources).find(f => f.endsWith(".tar.zst"));
  if (zstFile) {
    console.log(`  Pre-extracting self-extracting bundle...`);
    const buildDir = resolve(paths.app, "..");
    const zstPath = join(resources, zstFile);
    const tarPath = join(buildDir, `${APP_NAME}.app.tar`);

    // zig-zstd lives in electrobun's dist, not inside the self-extracting wrapper
    const zigZstd = resolve(ROOT, "node_modules/electrobun/dist-macos-arm64/zig-zstd");
    if (!existsSync(zigZstd)) {
      console.warn(`  ⚠ zig-zstd not found at ${zigZstd}, skipping pre-extraction`);
    } else {
      const dec = Bun.spawnSync([zigZstd, "decompress", "-i", zstPath, "-o", tarPath], {
        cwd: buildDir, stdout: "inherit", stderr: "inherit",
      });
      if (!dec.success) throw new Error("zig-zstd decompress failed");

      // Remove the self-extracting wrapper
      rmSync(paths.app, { recursive: true });

      // Untar the real app bundle
      const untar = Bun.spawnSync(["tar", "-xf", tarPath, "-C", buildDir], {
        cwd: buildDir, stdout: "inherit", stderr: "inherit",
      });
      if (!untar.success) throw new Error("tar extract failed");

      // Clean up
      rmSync(tarPath, { force: true });
      console.log(`  Extracted → ready-to-run app bundle (${await sizeOf(paths.app)})`);
    }
  }
}

// Cross-platform recursive size (avoids `du`, which doesn't exist on Windows).
async function sizeOf(path: string): Promise<string> {
  async function walk(p: string): Promise<number> {
    const s = statSync(p);
    if (!s.isDirectory()) return s.size;
    let total = 0;
    for (const entry of await readdir(p)) total += await walk(join(p, entry));
    return total;
  }
  const bytes = await walk(path);
  return `${(bytes / 1024 / 1024).toFixed(1)}M`;
}

// Post-build: stamp the Setup.exe installer with the icon too (it's
// generated by electrobun after our pre-build stamp of bun.exe/launcher.exe).
if (isWin) {
  const rcedit = resolve(ROOT, "node_modules/rcedit/bin/rcedit-x64.exe");
  const ico = resolve(ROOT, "icon.ico");
  if (existsSync(rcedit) && existsSync(ico) && paths.setup && existsSync(paths.setup)) {
    try {
      await $`${rcedit} ${paths.setup} --set-icon ${ico} --set-version-string ProductName ${APP_NAME} --set-version-string FileDescription ${APP_NAME} --set-file-version 0.1.0 --set-product-version 0.1.0`.quiet();
      console.log(`  icon+meta → ${paths.setup}`);
    } catch (e) {
      console.warn(`  ⚠ rcedit failed for Setup.exe: ${e}`);
    }
  }
}

console.log(`\n=== supergit build complete ===\n`);

for (const [label, path] of Object.entries(paths)) {
  if (existsSync(path)) {
    console.log(`  ${label.padEnd(7)} ${path}  (${await sizeOf(path)})`);
  }
}

// Open / focus the output directory so the user can grab the installer.
const shouldOpenOutput = process.env.SUPERGIT_BUILD_OPEN_OUTPUT !== "0";
if (shouldOpenOutput && paths.app && existsSync(paths.app)) {
  const appDir = resolve(paths.app, "..");
  console.log(`\n  Opening:  ${appDir}\n`);
  Bun.spawn(["open", appDir], { stdio: ["ignore", "ignore", "ignore"] });
} else if (shouldOpenOutput && isWin && paths.setup && existsSync(paths.setup)) {
  const setupDir = resolve(paths.setup, "..");
  console.log(`\n  Opening:  ${setupDir}\n`);
  Bun.spawn(["explorer.exe", setupDir], { stdio: ["ignore", "ignore", "ignore"] });
}
